name: build and push to ghcr
on:
    pull_request:
    schedule:
        - cron: "0 0 * * 6"
    push:
    workflow_dispatch:
env:
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
    push-ghcr:
        name: Build and push containers
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write
        strategy:
            fail-fast: false
            matrix:
                dockerfile:
                    - soju/Dockerfile

        steps:
            # Checkout push-to-registry action GitHub repository
            - name: git clone
              uses: actions/checkout@v4

            - name: steal environment variables
              run: echo "IMAGE_NAME=$(echo ${{ matrix.dockerfile }} | cut -d . -f 1 | cut -d '/' -f 1)" >> $GITHUB_ENV

            # Build metadata
            - name: apply image metadata
              uses: docker/metadata-action@v5
              id: meta
              with:
                  images: |
                      ${{ env.IMAGE_NAME }}
                  labels: |
                      org.opencontainers.image.title=${{ env.IMAGE_NAME }}
                      org.opencontainers.image.description=${{ env.IMAGE_NAME }} is an automatically built package

            - name: generate tags
              id: generate-tags
              shell: bash
              run: |
                  # Generate a timestamp for creating an image version history
                  TIMESTAMP="$(date +%Y%m%d)"
                  COMMIT_TAGS=()
                  BUILD_TAGS=()
                  # Have tags for tracking builds during pull request
                  SHA_SHORT="${GITHUB_SHA::7}"
                  COMMIT_TAGS+=("pr-${{ github.event.number }}")
                  COMMIT_TAGS+=("${SHA_SHORT}")

                  BUILD_TAGS+=("${TIMESTAMP}")
                  BUILD_TAGS+=("latest")

                  if [[ "${{ github.event_name }}" == "pull_request" ]]; then
                      echo "Generated the following commit tags: "
                      for TAG in "${COMMIT_TAGS[@]}"; do
                          echo "${TAG}"
                      done
                      alias_tags=("${COMMIT_TAGS[@]}")
                  else
                      alias_tags=("${BUILD_TAGS[@]}")
                  fi
                  echo "Generated the following build tags: "
                  for TAG in "${BUILD_TAGS[@]}"; do
                      echo "${TAG}"
                  done
                  echo "alias_tags=${alias_tags[*]}" >> $GITHUB_OUTPUT

            # Build image using Buildah action
            - name: build image
              id: build_image
              uses: redhat-actions/buildah-build@v2
              with:
                  containerfiles: "${{ matrix.dockerfile }}"
                  image: ${{ env.IMAGE_NAME }}
                  tags: |
                      ${{ steps.generate-tags.outputs.alias_tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  oci: false

            # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
            # https://github.com/macbre/push-to-ghcr/issues/12
            - name: Lowercase Registry
              id: registry_case
              uses: ASzc/change-string-case-action@v6
              with:
                  string: ${{ env.IMAGE_REGISTRY }}

            # Push the image to GHCR (Image Registry)
            - name: push image
              uses: redhat-actions/push-to-registry@v2
              id: push
              if: github.event_name != 'pull_request'
              env:
                  REGISTRY_USER: ${{ github.actor }}
                  REGISTRY_PASSWORD: ${{ github.token }}
              with:
                  image: ${{ steps.build_image.outputs.image }}
                  tags: ${{ steps.build_image.outputs.tags }}
                  registry: ${{ steps.registry_case.outputs.lowercase }}
                  username: ${{ env.REGISTRY_USER }}
                  password: ${{ env.REGISTRY_PASSWORD }}
                  extra-args: |
                      --disable-content-trust

            - name: hack into the mainframe (ghcr login)
              uses: docker/login-action@v3
              if: github.event_name != 'pull_request'
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: echo outputs
              if: github.event_name != 'pull_request'
              run: |
                  echo "${{ toJSON(steps.push.outputs) }}"
